-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES TABLE
create table if not exists public.profiles (
  id uuid primary key,
  phone text unique not null,
  name text,
  avatar text,
  status text default 'online',
  last_seen timestamptz default now()
);

-- MESSAGES TABLE
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  chat_id text not null,
  sender_id uuid references public.profiles(id) not null,
  recipient_id uuid references public.profiles(id), -- Nullable for group chats or broadcast
  content text,
  type text default 'TEXT',
  timestamp timestamptz default now(),
  is_read boolean default false
);

-- STATUSES TABLE
create table if not exists public.statuses (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  image_url text not null,
  caption text,
  timestamp timestamptz default now()
);

-- ROW LEVEL SECURITY (RLS)
-- Enabling "Public" access since the app handles auth client-side

alter table public.profiles enable row level security;
alter table public.messages enable row level security;
alter table public.statuses enable row level security;

-- PROFILES POLICIES
create policy "Public Usage Profiles"
on public.profiles for all
using (true)
with check (true);

-- MESSAGES POLICIES
create policy "Public Usage Messages"
on public.messages for all
using (true)
with check (true);

-- STATUSES POLICIES
create policy "Public Usage Statuses"
on public.statuses for all
using (true)
with check (true);

-- REALTIME SETUP
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime for table public.messages, public.profiles, public.statuses;
commit;
